name: Publish Python 🐍 distribution to PyPI

on:
  push:
    branches:
      - master  # Или ваша основная ветка, например 'master'

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu для сборки

    steps:
      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v2

      # Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Укажите нужную версию Python

      # Устанавливаем зависимости для сборки пакета
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Собираем пакет
      - name: Build the package
        run: python -m build

      # Публикуем на PyPI
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*
